# Generated by Django 4.2.6 on 2023-11-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer'), ('K', 'Niño')], max_length=1, null=True),
        ),
    ]
