# Generated by Django 4.2.6 on 2023-11-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_category_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('N', 'Niño')], default='H', max_length=1),
        ),
    ]
