# Generated by Django 4.2.6 on 2023-11-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_remove_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('niño', 'Niño')], default='H', max_length=7),
        ),
    ]
